export VLLM_USE_V1=1

N_GPUS=8
TP=1
INPUT_REWARD=0.1
MODEL_NAME=Shiyu-Lab/HarnessLLM_SFT_Qwen3_4B
TEST_HARNESS=True
PROMPT_FILE=harness

MAX_PROMPT_LEN=3072
MAX_RESPONSE_LEN=16384
ACTOR_PPO_MAX_TOKEN=$((MAX_PROMPT_LEN + MAX_RESPONSE_LEN + 5120))
INFER_PPO_MAX_TOKEN=$((ACTOR_PPO_MAX_TOKEN * 4))
STEP_BATCH_SIZE=128
DATA_CLASS=dynamictestcase

RUN_NAME="Qwen3_prompt@${PROMPT_FILE}_inputreward@${INPUT_REWARD}_length@${MAX_RESPONSE_LEN}"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=Shiyu-Lab/Testcase_RL_Data \
    data.val_files=Shiyu-Lab/Testcase_eval_data \
    data.train_batch_size=$STEP_BATCH_SIZE \
    data.val_batch_size=1312 \
    data.max_prompt_length=$MAX_PROMPT_LEN \
    data.max_response_length=$MAX_RESPONSE_LEN \
    data.data_class=$DATA_CLASS \
    data.prompt_file=prompts/${PROMPT_FILE}.py \
    data.filter_overlong_prompts=True \
    actor_rollout_ref.model.path=$MODEL_NAME \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=$ACTOR_PPO_MAX_TOKEN \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=$INFER_PPO_MAX_TOKEN \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=$INFER_PPO_MAX_TOKEN \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.overlong_filtering=False \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$INFER_PPO_MAX_TOKEN \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$TP \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.9 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.top_p=1 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.0 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='HarnessLLM' \
    trainer.experiment_name=$RUN_NAME \
    trainer.n_gpus_per_node=$N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=10 \
    trainer.total_training_steps=500 \
    trainer.remove_previous_ckpt_in_save=True \
    trainer.use_custom=True \
    trainer.val_before_train=False \
    trainer.default_local_dir=checkpoints/verl-code/${RUN_NAME} \
    reward_model.reward_manager=naive_parallel_ray \
    reward_compute_score.test_harness=$TEST_HARNESS \
    reward_compute_score.wrong_test_penalty=0.0 \
    reward_compute_score.num_testcases=20 \
    reward_compute_score.good_input_reward=$INPUT_REWARD